followalong3/Models/ButtonModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace followalong3.Models
{
    public class ButtonModel
    {
        public int Id { get; set; }
        public int ButtonState { get; set; }
    }
}

followalong3/Models/ErrorViewModel.cs
using System;

namespace followalong3.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

followalong3/Controllers/ButtonController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using followalong3.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.AspNetCore.Mvc.ViewFeatures;

namespace followalong3.Controllers
{
    public class ButtonController : Controller
    {
        static List<ButtonModel> buttons = new List<ButtonModel>();
        Random rand = new Random();
        const int GRID_SIZE = 25;
        public IActionResult Index()
        {
            if (buttons.Count < GRID_SIZE)
            {
                for (int i = 0; i < GRID_SIZE; i++)
                {
                    buttons.Add(new ButtonModel { Id = i, ButtonState = rand.Next(5) });
                }
            }
            return View("Index", buttons);
        }

        public IActionResult HandleButtonClick(string buttonNumber)
        {
            int btn = int.Parse(buttonNumber);
            buttons.ElementAt(btn).ButtonState = (buttons.ElementAt(btn).ButtonState + 1) % 5;
            return View("Index", buttons);
        }

        public IActionResult ShowOneButton(int buttonNumber)
        {
            // add one to the button state. if it's > 5, set it to 0
            buttons.ElementAt(buttonNumber).ButtonState = (buttons.ElementAt(buttonNumber).ButtonState + 1) % 5;

            // Render a button and save it to a string
            string buttonstr = RenderRazorViewToString(this, "ShowOneButton", buttons.ElementAt(buttonNumber));

            // Generate a win or loss string based on the state of the buttons array
            bool flag = true;
            for (int i = 0; i < buttons.Count; i++)
            {
                if (buttons.ElementAt(i).ButtonState != buttons.ElementAt(0).ButtonState)
                {
                    flag = false;
                }
            }

            string nyeh;
            if (flag)
            {
                nyeh = "<p>All of the buttons are the same color</p>";
            } else
            {
                nyeh = "<p>Try and get all the buttons to be the same color</p>";
            }

            // Assemble a JSON string that has 2 parts (button string html and win loss message)
            var package = new { part1 = buttonstr, part2 = nyeh };

            // Send the JSON result
            return Json(package);

            // In site.js, the data will have to be interpreted as 2 pieces of data instead of one

        }

        public static string RenderRazorViewToString(Controller controller, string viewName, object model = null)
        {
            controller.ViewData.Model = model;
            using (var sw = new StringWriter())
            {
                IViewEngine viewEngine =
                    controller.HttpContext.RequestServices.GetService(typeof(ICompositeViewEngine)) as
                        ICompositeViewEngine;
                ViewEngineResult viewResult = viewEngine.FindView(controller.ControllerContext, viewName, false);

                ViewContext viewContext = new ViewContext(
                    controller.ControllerContext,
                    viewResult.View,
                    controller.ViewData,
                    controller.TempData,
                    sw,
                    new HtmlHelperOptions()
                );
                viewResult.View.RenderAsync(viewContext);
                return sw.GetStringBuilder().ToString();
            }
        }
    }
}

followalong3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using followalong3.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace followalong3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

followalong3/Views/Button/Index.cshtml
@model IEnumerable<followalong3.Models.ButtonModel>

<style>
    .game-button {
        width:74px;
        text-align:center;
        border:none;
    }
    .game-button-image {
        width:70%;
    }
    .button-zone {
        display:flex;
        flex-wrap:wrap;
    }
    .line-break {
        flex-basis:100%;
        height:0;
    }
    .button-label {
        font-size:8px;
        text-align:center;
    }
</style>

@{ 
    string[] imagenames = { "bluebutton.png", "greenbutton.png", "orangebutton.png", "pinkbutton.png", "redbutton.png" };
}

<form>
    <div class="button-zone">

        @for (int i = 0; i < Model.Count(); i++)
        {
            @if (i % 5 == 0)
            {
                <div class="line-break"></div>
            }
            <div class="oneButton" id="@i">
                <button class="game-button" name="buttonNumber" value="@Model.ElementAt(i).Id" type="submit" asp-controller="button" asp-action="HandleButtonClick">
                <img class="game-button-image" src="~/img/@imagenames[Model.ElementAt(i).ButtonState]" />

                <div class="button-label">
                    @Model.ElementAt(i).Id | @Model.ElementAt(i).ButtonState
                </div>
            </button>
            </div>
        }

    </div>
</form>

<div id="messageArea">
    <p>Try and get all the buttons to be the same color</p>
</div>

followalong3/Views/Button/ShowOneButton.cshtml
@model followalong3.Models.ButtonModel

@{
    string[] imagenames = { "bluebutton.png", "greenbutton.png", "orangebutton.png", "pinkbutton.png", "redbutton.png" };
    bool allMatch = true;
}

<button class="game-button" name="buttonNumber" value="@Model.Id" type="submit" asp-controller="button" asp-action="HandleButtonClick">
    <img class="game-button-image" src="~/img/@imagenames[Model.ButtonState]" />

    <div class="button-label">
        @Model.Id | @Model.ButtonState
    </div>
</button>

followalong3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

followalong3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - followalong3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">followalong3</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Button" asp-action="Index">Button Grid Game</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - followalong3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>